name: Sync Sanity Production to Dev Dataset

on:
  workflow_dispatch:
  create:
    branches: # Trigger only when a branch is created
      - "*"

jobs:
  prepare-datasets:
    runs-on: ubuntu-latest
    name: Sync 'production' to 'dev'
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
        with:
          args: dataset export production production.tar.gz --overwrite

      - name: Delete existing 'dev' dataset
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
        with:
          args: dataset delete dev --force

      - name: Create new 'dev' dataset
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
        with:
          args: dataset create dev

      - name: Import 'production' into new 'dev' dataset
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_PROJECT }}
        with:
          args: dataset import production.tar.gz dev

      - name: Clean up exported file
        run: rm production.tar.gz
