name: Sync Sanity Production to Dev Dataset

on:
  workflow_dispatch:
  create:
    branches: # Trigger only when a branch is created
      - "*"

jobs:
  prepare-datasets:
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      SANITY_STUDIO_PROJECT_ID: ${{ vars.SANITY_STUDIO_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          npm install

      - name: Export 'production' dataset
        run: |
          npx -y sanity@latest dataset export production production.tar.gz --overwrite

      - name: Delete existing 'dev' dataset
        run: |
          npx -y sanity@latest dataset delete dev --force

      - name: Create new 'dev' dataset
        run: |
          npx -y sanity@latest dataset create dev --visibility public

      - name: Import data into new 'dev' dataset
        run: |
          npx -y sanity@latest dataset import production.tar.gz dev --replace

      - name: Clean up exported file
        run: rm production.tar.gz
